### ISSUE TITLE
travis builds failing from missing envvar

### ISSUE THREAD

**Issue by zerosignal0** [ianunruh/python-vaultclient#4]
Seems the travis builds are a bit flakey due to the settings / retrieval of the vault token env var.  

Might I suggest potentially considering reading from the $HOME/.vault-token file within your tests and setting the var?  Admittedly not quite as clean, but would avoid these types of issues in the future, and would potentially make the code more portable to other build systems.

**Comment by ianunruh** [comment]
I'm currently working on refactoring the way that tests are done so that the client initializes Vault and saves the keys in memory. I'll be including this in `master` soon.

**Comment by ianunruh** [comment]
Fixed in 322460d6f752057ac76a2c530dd53886faf7fd27
